version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x

  pre_build:
    commands:
      - cd cicd # Change directory
      - ./install-terraform.sh # Install Terraform
      - ./configure-named-profile.sh # Configure named profile

  build:
    commands:
      - ./apply-terraform.sh
